# Generated by Django 3.2.12 on 2023-10-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_profissional_saude', models.CharField(max_length=150)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=11, unique=True)),
                ('tipo_profissional', models.CharField(max_length=150)),
                ('conselho', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id_vacina', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_vacina', models.CharField(max_length=150)),
                ('profissional', models.CharField(max_length=150)),
                ('data_vacina', models.DateField()),
                ('lote', models.CharField(max_length=150)),
                ('fabricante', models.CharField(max_length=150)),
                ('data_fabricacao', models.DateField()),
                ('id_agendamento', models.CharField(max_length=150)),
            ],
        ),
    ]
