# Generated by Django 4.2 on 2023-10-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id_vacina', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_vacina', models.CharField(max_length=50)),
                ('profissional', models.CharField(max_length=50)),
                ('data_vacina', models.DateField()),
                ('lote', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
                ('data_fabricacao', models.DateField()),
                ('id_agendamento', models.CharField(max_length=50)),
            ],
        ),
    ]
